apiVersion: monitoring.openshift.io/v1
kind: AlertingRule
metadata:
  name: ContainerKilled
spec:
  annotations:
    description: '"A container has disappeared\n  VALUE = {{ $value }}\n  LABELS =
      {{ $labels }}"'
    summary: Container killed (instance {{ $labels.instance }})
  expr: time() - container_last_seen > 60
  for: 0m
  labels:
    severity: warning
