apiVersion: monitoring.openshift.io/v1
kind: AlertingRule
metadata:
  name: ContainerHighCpuUtilization
spec:
  annotations:
    description: '"Container CPU utilization is above 80%\n  VALUE = {{ $value }}\n  LABELS
      = {{ $labels }}"'
    summary: Container High CPU utilization (instance {{ $labels.instance }})
  expr: (sum(rate(container_cpu_usage_seconds_total{container!=""}[5m])) by (pod,
    container) / sum(container_spec_cpu_quota{container!=""}/container_spec_cpu_period{container!=""})
    by (pod, container) * 100) > 80
  for: 2m
  labels:
    severity: warning
