apiVersion: monitoring.openshift.io/v1
kind: AlertingRule
metadata:
  name: ContainerAbsent
spec:
  annotations:
    description: '"A container is absent for 5 min\n  VALUE = {{ $value }}\n  LABELS
      = {{ $labels }}"'
    summary: Container absent (instance {{ $labels.instance }})
  expr: absent(container_last_seen)
  for: 5m
  labels:
    severity: warning
