apiVersion: monitoring.openshift.io/v1
kind: AlertingRule
metadata:
  name: KubernetesNodeOutOfPodCapacity
spec:
  annotations:
    description: '"Node {{ $labels.node }} is out of pod capacity\n  VALUE = {{ $value
      }}\n  LABELS = {{ $labels }}"'
    summary: Kubernetes Node out of pod capacity (instance {{ $labels.instance }})
  expr: sum by (node) ((kube_pod_status_phase{phase="Running"} == 1) + on(uid) group_left(node)
    (0 * kube_pod_info{pod_template_hash=""})) / sum by (node) (kube_node_status_allocatable{resource="pods"})
    * 100 > 90
  for: 2m
  labels:
    severity: warning
