apiVersion: monitoring.openshift.io/v1
kind: AlertingRule
metadata:
  name: KubernetesDaemonsetMisscheduled
spec:
  annotations:
    description: '"Some Pods of DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset
      }} are running where they are not supposed to run\n  VALUE = {{ $value }}\n  LABELS
      = {{ $labels }}"'
    summary: Kubernetes DaemonSet misscheduled (instance {{ $labels.instance }})
  expr: kube_daemonset_status_number_misscheduled > 0
  for: 1m
  labels:
    severity: critical
