apiVersion: monitoring.openshift.io/v1
kind: AlertingRule
metadata:
  name: KubernetesHpaScaleMaximum
spec:
  annotations:
    description: '"HPA {{ $labels.namespace }}/{{ $labels.horizontalpodautoscaler
      }} has hit maximum number of desired pods\n  VALUE = {{ $value }}\n  LABELS
      = {{ $labels }}"'
    summary: Kubernetes HPA scale maximum (instance {{ $labels.instance }})
  expr: (kube_horizontalpodautoscaler_status_desired_replicas >= kube_horizontalpodautoscaler_spec_max_replicas)
    and (kube_horizontalpodautoscaler_spec_max_replicas > 1) and (kube_horizontalpodautoscaler_spec_min_replicas
    != kube_horizontalpodautoscaler_spec_max_replicas)
  for: 2m
  labels:
    severity: info
