apiVersion: monitoring.openshift.io/v1
kind: AlertingRule
metadata:
  name: KubernetesApiServerLatency
spec:
  annotations:
    description: '"Kubernetes API server has a 99th percentile latency of {{ $value
      }} seconds for {{ $labels.verb }} {{ $labels.resource }}.\n  VALUE = {{ $value
      }}\n  LABELS = {{ $labels }}"'
    summary: Kubernetes API server latency (instance {{ $labels.instance }})
  expr: histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{verb!~"(?:CONNECT|WATCHLIST|WATCH|PROXY)"}
    [10m])) WITHOUT (subresource)) > 1
  for: 2m
  labels:
    severity: warning
