apiVersion: monitoring.openshift.io/v1
kind: AlertingRule
metadata:
  name: KubernetesPodCrashLooping
spec:
  annotations:
    description: '"Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping\n  VALUE
      = {{ $value }}\n  LABELS = {{ $labels }}"'
    summary: Kubernetes pod crash looping (instance {{ $labels.instance }})
  expr: increase(kube_pod_container_status_restarts_total[1m]) > 3
  for: 2m
  labels:
    severity: warning
