apiVersion: monitoring.openshift.io/v1
kind: AlertingRule
metadata:
  name: KubernetesPersistentvolumeError
spec:
  annotations:
    description: '"Persistent volume {{ $labels.persistentvolume }} is in bad state\n  VALUE
      = {{ $value }}\n  LABELS = {{ $labels }}"'
    summary: Kubernetes PersistentVolume error (instance {{ $labels.instance }})
  expr: kube_persistentvolume_status_phase{phase=~"Failed|Pending", job="kube-state-metrics"}
    > 0
  for: 0m
  labels:
    severity: critical
