apiVersion: monitoring.openshift.io/v1
kind: AlertingRule
metadata:
  name: KubernetesApiClientErrors
spec:
  annotations:
    description: '"Kubernetes API client is experiencing high error rate\n  VALUE
      = {{ $value }}\n  LABELS = {{ $labels }}"'
    summary: Kubernetes API client errors (instance {{ $labels.instance }})
  expr: (sum(rate(rest_client_requests_total{code=~"(4|5).."}[1m])) by (instance,
    job) / sum(rate(rest_client_requests_total[1m])) by (instance, job)) * 100 > 1
  for: 2m
  labels:
    severity: critical
