apiVersion: monitoring.openshift.io/v1
kind: AlertingRule
metadata:
  name: high-node-memory-usage-alert
  namespace: openshift-monitoring 
spec:
  groups:
  - name: high-node-memory-usage-alert
    rules:
    - alert: HighNodeMemoryUsageAlert 
      for: 1m 
      expr: |
        (
          1
          -
          sum by (instance) (
            node_memory_MemFree_bytes
            + node_memory_Buffers_bytes
            + node_memory_Cached_bytes
          ) / sum by (instance) (
            node_memory_MemTotal_bytes
          )
        ) * 100 > 80
      labels:
        severity: warning 
      annotations:
        descriptions: {{ $labels.instance }} is higher than 80% memory usage.
---
apiVersion: monitoring.openshift.io/v1
kind: AlertingRule
metadata:
  name: high-node-cpu-usage-alert
  namespace: openshift-monitoring 
spec:
  groups:
  - name: high-node-cpu-usage-alert
    rules:
    - alert: HighNodeCPUUsageAlert 
      for: 1m 
      expr: |
        (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
      labels:
        severity: warning 
      annotations:
        descriptions: {{ $labels.instance }} is higher than 80% CPU usage.
		