apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cronjob-alert
spec:
  groups:
  - name: jobsfailedrule
    rules:
    - alert: JobFailing
      annotations:
        message: Job {{ $labels.namespace }}/{{ $labels.job_name }} failed to complete.
      expr: |
        kube_job_status_failed{job="kube-state-metrics"} > 0
      for: 5m
      labels:
        severity: warning