apiVersion: monitoring.openshift.io/v1
kind: AlertingRule
metadata:
  name: oom-alert
  namespace: openshift-monitoring
spec:
  groups:
  - name: OOM
    rules:
    - alert: PodOOMKilled
      annotations:
        description: Container {{ $labels.container }} is OOM killed in Pod {{ $labels.pod
          }}
        summary: Pod is OOMKilled  {{ $labels.pod }}
      expr: kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}
      labels:
        severity: warning
