apiVersion: monitoring.openshift.io/v1
kind: AlertingRule
metadata:
  name: pod-crashloopbackoff-alert
  namespace: openshift-monitoring
spec:
  groups:
  - name: pod-crashloopbackoff-group
    rules:
    - alert: PodCrashLoopBackOff
      expr: |
        max_over_time(
          kube_pod_container_status_waiting_reason{
            job="kube-state-metrics",
            reason="CrashLoopBackOff",
            namespace!~"(openshift-.*|kube-.*|default)"
          }[5m]
        ) >= 1
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Pod in CrashLoopBackOff nel namespace {{ $labels.namespace }}"
        description: "Il pod {{ $labels.pod }} nel namespace {{ $labels.namespace }} è in CrashLoopBackOff da almeno 2 minuti"