apiVersion: monitoring.openshift.io/v1
kind: AlertingRule
metadata:
  name: pod-restarts-alert
  namespace: openshift-monitoring
spec:
  groups:
  - name: pod-restarts-alert
    rules:
    - alert: PodRestartsAlert
      for: 5m
      expr: |
        sum by (pod, namespace) (increase(kube_pod_container_status_restarts_total{namespace!~"openshift-.*|kube-.*"}[1h])) > 1
      labels:
        severity: warning
      annotations:
        description: "The pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted more than 5 times in the last hour."
